[package]
name = "wiscanet-gui"
version = "0.1.0"
authors = ["Jacob Holtom <jacob@holtom.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
